# Have to scan QR code everytime
is_forced_switch: False

#--------------------------------------Set up auto reply--------------------------------------start
auto_reply_info:
  # Whether start to reply.
  is_auto_reply: True

  # Whether to reply to all the friends (only black list members will not be replied).
  is_auto_reply_all: True

  # auto reply prefix
  auto_reply_prefix: 'ğŸ¯ '
  # auto reply suffix
  auto_reply_suffix: '  -- Team666 Bee ğŸ'

  # White list
  auto_reply_white_list:
    - 'æ–‡ä»¶ä¼ è¾“åŠ©æ‰‹'

  # Black list
  auto_reply_black_list:
    - 'è´´å¿ƒå°ç§˜ä¹¦'

  # Robot channel (1: Turing Robot, 3: Qingyunke, 4: Zhinengxianliao, 5:Tianxing Robot, 6ï¼šHaizhi AI, 7ï¼šSizhi Robot)
  bot_channel: 7

  # Turing Robot http://www.tuling123.com/
  turing_conf:
    apiKey: 'ä½ ç”³è¯·çš„apikey'

  # Tianxing Robot https://www.tianapi.com/apiview/47
  txapi_conf:
    app_key: 'ä¸ªäººä¸­å¿ƒä¸­çš„key'
    reply_name: 'å®å®'
    bot_name: 'è€å…¬' 

  # Zhinengxianliao https://ai.qq.com/product/nlpchat.shtml
  qqnlpchat_conf:
    app_id: 'ä½ ç”³è¯·çš„api_id'
    app_key: 'ä½ ç”³è¯·çš„app_key'

  # Haizhi AI https://ruyi.ai/
  ruyi_conf:
    app_key: 'ä½ ç”³è¯·çš„key'

  # Sizhi Robot https://www.ownthink.com/
  ownthink_conf:
    app_key: ''



#--------------------------------------Set up auto reply--------------------------------------end


#--------------------------------------Group Chat Helper Settings--------------------------------------start

group_helper_conf:
  is_open: True # Open group assistant
  is_all: False # Whether open for all the groups. When opened, only groups in black list will not be affected.

  # White list members. When is_all == False, only reply to groups listed here.
  group_name_white_list:
    - 'Team666'

  # Black list members. When is_all == True, the groups listed here will not be replied.
  group_name_black_list:
    - 'CSé¸½é¸½ç¾¤'
    - 'CSå­¦ä¹ ç¾¤'

  is_at: True # for @. Only when the robot is @, it handles the messages.
  is_auto_reply: True # Start auto reply to group chat


#--------------------------------------Group Chat Helper Settings--------------------------------------end


#--------------------------------------Database Settings--------------------------------------start
# This database is for the group assistant to query the cache of data.
db_config: # Need to install mongodb database.
  is_open_db: True # Whether to turn on database function.
  mongodb_conf:
    'host': 'localhost'
    'port': 27017
#--------------------------------------Database Settings--------------------------------------end